config/routes.rb
Rails.application.routes.draw do
  resources :service_entries
  resources :employees
  patch 'roles/update_permissions', to:"roles#update_permissions", as: "update_permissions"
  get 'roles/permissions/:id', to:"roles#permissions", as: "role_permissions"
  resources :roles
  # get "roles", to:"roles#index"
  # post 'roles', to:"roles#create"
  # delete 'roles/:id', to:"roles#destroy" 
  resources :vehicles
  namespace :admin do
    get 'users/assign_role/:id', to:"users#assign_role", as:"assign_role"
    
    resources :users
    
  end
  get 'home', to:"home#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/service_entry.rb
class ServiceEntry < ApplicationRecord
end

app/controllers/service_entries_controller.rb
class ServiceEntriesController < ApplicationController
  before_action :set_service_entry, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /service_entries
  def index
    @service_entries = ServiceEntry.all
  end

  # GET /service_entries/1
  def show
  end

  # GET /service_entries/new
  def new
    @service_entry = ServiceEntry.new
  end

  # GET /service_entries/1/edit
  def edit
  end

  # POST /service_entries
  def create
    @service_entry = ServiceEntry.new(service_entry_params)

    if @service_entry.save
      redirect_to @service_entry, notice: 'Service entry was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /service_entries/1
  def update
    if @service_entry.update(service_entry_params)
      redirect_to @service_entry, notice: 'Service entry was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /service_entries/1
  def destroy
    @service_entry.destroy
    redirect_to service_entries_url, notice: 'Service entry was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_entry
      @service_entry = ServiceEntry.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def service_entry_params
      params.require(:service_entry).permit(:name, :vehicle_id, :tax, :total, :service_date)
    end
end

app/helpers/service_entries_helper.rb
module ServiceEntriesHelper
end

app/views/service_entries/_form.html.erb
<%= form_with(model: service_entry, local: true) do |form| %>
  <% if service_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service_entry.errors.count, "error") %> prohibited this service_entry from being saved:</h2>

      <ul>
      <% service_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :vehicle_id %>
    <%= form.number_field :vehicle_id %>
  </div>

  <div class="field">
    <%= form.label :tax %>
    <%= form.text_field :tax %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total %>
  </div>

  <div class="field">
    <%= form.label :service_date %>
    <%= form.datetime_select :service_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/service_entries/edit.html.erb
<h1>Editing Service Entry</h1>

<%= render 'form', service_entry: @service_entry %>

<%= link_to 'Show', @service_entry %> |
<%= link_to 'Back', service_entries_path %>

app/views/service_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Service Entries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Vehicle</th>
      <th>Tax</th>
      <th>Total</th>
      <th>Service date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_entries.each do |service_entry| %>
      <tr>
        <td><%= service_entry.name %></td>
        <td><%= service_entry.vehicle_id %></td>
        <td><%= service_entry.tax %></td>
        <td><%= service_entry.total %></td>
        <td><%= service_entry.service_date %></td>
        <td><%= link_to 'Show', service_entry %></td>
        <td><%= link_to 'Edit', edit_service_entry_path(service_entry) %></td>
        <td><%= link_to 'Destroy', service_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service Entry', new_service_entry_path %>

app/views/service_entries/new.html.erb
<h1>New Service Entry</h1>

<%= render 'form', service_entry: @service_entry %>

<%= link_to 'Back', service_entries_path %>

app/views/service_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service_entry.name %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @service_entry.vehicle_id %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @service_entry.tax %>
</p>

<p>
  <strong>Total:</strong>
  <%= @service_entry.total %>
</p>

<p>
  <strong>Service date:</strong>
  <%= @service_entry.service_date %>
</p>

<%= link_to 'Edit', edit_service_entry_path(@service_entry) %> |
<%= link_to 'Back', service_entries_path %>