config/routes.rb
Rails.application.routes.draw do
  resources :service_entries
  resources :employees
  patch 'roles/update_permissions', to:"roles#update_permissions", as: "update_permissions"
  get 'roles/permissions/:id', to:"roles#permissions", as: "role_permissions"
  resources :roles
  # get "roles", to:"roles#index"
  # post 'roles', to:"roles#create"
  # delete 'roles/:id', to:"roles#destroy" 
  resources :vehicles
  namespace :admin do
    get 'users/assign_role/:id', to:"users#assign_role", as:"assign_role"
    
    resources :users
    
  end
  get 'home', to:"home#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # belongs_to :role
  has_many :user_role
  has_many :roles, through: :user_role
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:edit,:update,:destroy,:assign_role]
  load_and_authorize_resource
  def index
    @users = User.includes(:roles)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "User created successfully"
    else
      flash[:alert] = "Something went wrong"
      redirect_back(fallback_location: root_path)
    end    
  end

  def new
    @user = User.new
  end
  
  def edit
  end

  def update
    if @user.update(user_params)
      # flash[:notice] = "User updated successfully"
      # redirect_back(fallback_location: root_path)
      redirect_to admin_users_path, notice: "User updated successfully"
    else
      flash[:alert] = "Something went wrong"
      redirect_back(fallback_location: root_path)
    end    
  end
  
  def destroy
    @user.destroy
    flash[:notice] = "User destroyed successfully"
    redirect_back(fallback_location: root_path)
  end

  
  
  def assign_role
    
  end
  

  private 

    def set_user
      @user = User.find(params[:id])
    end
    
    def user_params
      params.require(:user).permit(:email,:password,:role_ids)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit,:update,:destroy]
  
  def index
    @users = User.where(is_admin: false)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User created successfully"
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = "Something went wrong"
      redirect_back(fallback_location: root_path)
    end    
  end

  def new
    @user = User.new
  end
  
  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User updated successfully"
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = "Something went wrong"
      redirect_back(fallback_location: root_path)
    end    
  end
  
  def destroy
    @user.destroy
    flash[:notice] = "User destroyed successfully"
    redirect_back(fallback_location: root_path)
  end
  

  private 

    def set_user
      @user = User.find(params[:id])
    end
    
    def user_params
      params.require(:user).permit(:email,:password)
    end
    
end

app/views/admin/users/_form.html.erb
<%= form_for User.new, url: admin_users_path do |form| %>
  <div class="form-group">
    <%=form.label :email%>
    <%= form.text_field :email, class:"form-control"%>
  </div>
  <div class="form-group">
    <%=form.label :password%>
    <%= form.text_field :password, class:"form-control"%>
  </div>
  <%=form.submit nil%>
<%end%>

app/views/admin/users/assign_role.html.erb
<h1>Assign Role</h1>
<%= form_for @user, url: admin_user_path do |f| %>
  <div class="field">
    <%=f.collection_select :role_ids, Role.all, :id,:name%>
  </div>
  <%=f.submit "update"%>
<%end%>

app/views/admin/users/edit.html.erb
<%= render 'form', user: @user%>

app/views/admin/users/index.html.erb
<h1>Users list</h1>
<b><%#=link_to "Add User", new_admin_user_path%></b>
<%= button_to "Add User", new_admin_user_path, :method => "get" %>
<table class="table" border="1">
  <thead>
    <tr>
      <th>Email</th>
      <th>Role</th>
      <!--<th>Actions</th>-->
    </tr>
  </thead>
  <tbody>
    <%@users.each do |user|%>
      <tr>
        <td><%=user.email%></td>
        <td><%#= link_to "#{user.roles.present? ? user.roles.pluck(:name).join : "Not Assigned"}",admin_assign_role_path(user.id) %>
          <%= link_to "#{user.roles.pluck(:name).present? ? user.roles.pluck(:name).join : "Not Assigned"}",admin_assign_role_path(user.id) %>
          
        </td>
        <td><%#=link_to "set permission", admin_user_permissions_path(user.id) %></td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<%= render 'form', user: @user%>