config/routes.rb
Rails.application.routes.draw do
  resources :service_entries
  resources :employees
  patch 'roles/update_permissions', to:"roles#update_permissions", as: "update_permissions"
  get 'roles/permissions/:id', to:"roles#permissions", as: "role_permissions"
  resources :roles
  # get "roles", to:"roles#index"
  # post 'roles', to:"roles#create"
  # delete 'roles/:id', to:"roles#destroy" 
  resources :vehicles
  namespace :admin do
    get 'users/assign_role/:id', to:"users#assign_role", as:"assign_role"
    
    resources :users
    
  end
  get 'home', to:"home#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DynamicAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><h2><b><%= notice %></p>
    <p class="alert"><%= alert %></b></h2></p>
    <% if user_signed_in? %>
      <%= current_user.email %> |
      <%#= link_to "Account Settings", edit_user_registration_path %> | 
      <%= link_to "Logout", destroy_user_session_path, method: :delete %> |
      <%= link_to "Users", admin_users_path%> |
      <%= link_to "Roles", roles_path %> | 
      <%= link_to "Vehicles", vehicles_path%> |
      <%= link_to "Employees", employees_path%> |
      <%= link_to "ServiceEntries", service_entries_path%> 
    <% else %>
	    <%= link_to "Login", new_user_session_path %> | <%#= link_to "Register", new_user_registration_path %> 
    <% end %>
    
    <%= yield %>
  </body>
</html>